# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure ddclient paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ ddclient_uid }}"
    group: "{{ ddclient_gid }}"
  with_items:
    - "{{ ddclient_base_path }}"
    - "{{ ddclient_config_path }}"

- name: Ensure ddclient support file installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ ddclient_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ ddclient_uid }}"
    group: "{{ ddclient_gid }}"
  with_items:
    - env

- name: Ensure ddclient ddclient.conf installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/ddclient.conf.j2"
    dest: "{{ ddclient_config_path }}/ddclient.conf"
    mode: "0644"
    owner: "{{ ddclient_uid }}"
    group: "{{ ddclient_gid }}"

- name: Ensure ddclient image is pulled
  community.docker.docker_image:
    name: "{{ ddclient_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ ddclient_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else ddclient_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure ddclient container network is created
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ ddclient_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure ddclient systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/ddclient.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ ddclient_identifier }}.service"
    mode: "0644"
