# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure ddclient paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ ddclient_uid }}"
    group: "{{ ddclient_gid }}"
  with_items:
    - "{{ ddclient_base_path }}"
    - "{{ ddclient_config_path }}"

- name: Ensure ddclient support file installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ ddclient_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ ddclient_uid }}"
    group: "{{ ddclient_gid }}"
  with_items:
    - env

- name: Ensure ddclient ddclient.conf installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/ddclient.conf.j2"
    dest: "{{ ddclient_config_path }}/ddclient.conf"
    mode: "0644"
    owner: "{{ ddclient_uid }}"
    group: "{{ ddclient_gid }}"

- name: Run if self-building of ddclient container image is not enabled
  when: "not ddclient_container_image_self_build | bool"
  block:
    - name: Ensure ddclient container image is pulled via community.docker.docker_image
      when: devture_systemd_docker_base_container_image_pull_method == 'ansible-module'
      community.docker.docker_image:
        name: "{{ ddclient_container_image }}"
        source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
        force_source: "{{ ddclient_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
        force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else ddclient_container_image_force_pull }}"
      register: result
      retries: "{{ devture_playbook_help_container_retries_count }}"
      delay: "{{ devture_playbook_help_container_retries_delay }}"
      until: result is not failed

    - name: Ensure ddclient container image is pulled via ansible.builtin.command
      when: devture_systemd_docker_base_container_image_pull_method == 'command'
      ansible.builtin.command:
        cmd: "{{ devture_systemd_docker_base_host_command_docker }} pull {{ ddclient_container_image }}"
      register: result
      retries: "{{ devture_playbook_help_container_retries_count }}"
      delay: "{{ devture_playbook_help_container_retries_delay }}"
      until: result is not failed
      changed_when: "'Downloaded newer image' in result.stdout"

- name: Run if self-building of ddclient container image is enabled
  when: "ddclient_container_image_self_build | bool"
  block:
    - name: Ensure ddclient repository is present on self-build
      ansible.builtin.git:
        repo: "{{ ddclient_container_image_self_build_repo }}"
        version: "{{ ddclient_container_image_self_build_repo_version }}"
        dest: "{{ ddclient_container_image_self_build_src_files_path }}"
        force: "yes"
      register: ddclient_git_pull_results

    - name: Ensure ddclient container image is built
      community.docker.docker_image:
        name: "{{ ddclient_container_image_self_build_name }}"
        source: build
        force_source: "{{ ddclient_git_pull_results.changed if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
        force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else ddclient_git_pull_results.changed }}"
        build:
          dockerfile: Dockerfile
          path: "{{ ddclient_container_image_self_build_src_files_path }}"
          pull: true
          args:

- name: Ensure ddclient container network is created
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ ddclient_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure ddclient systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/ddclient.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ ddclient_identifier }}.service"
    mode: "0644"
