# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform ddclient installation tasks
  when: docker_registry_purger_enabled | bool
  tags:
    - setup-all
    - setup-docker-registry-purger
    - install-all
    - install-docker-registry-purger
  block:
    - name: Validate ddclient configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install ddclient
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform ddclient uninstallation tasks
  when: not docker_registry_purger_enabled | bool
  tags:
    - setup-all
    - setup-docker-registry-purger
  block:
    - name: Uninstall ddclient
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
