# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of ddclient systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ docker_registry_purger_identifier }}.service"
  register: docker_registry_purger_service_stat

- name: Uninstall ddclient systemd services and files
  when: docker_registry_purger_service_stat.stat.exists | bool
  block:
    - name: Ensure ddclient systemd services are stopped
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: false
        daemon_reload: true
      with_items:
        - "{{ docker_registry_purger_identifier }}.service"
        - "{{ docker_registry_purger_identifier }}.timer"

    - name: Ensure ddclient systemd services do not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ item }}"
        state: absent
      with_items:
        - "{{ docker_registry_purger_identifier }}.service"
        - "{{ docker_registry_purger_identifier }}.timer"

    - name: Ensure ddclient path does not exist
      ansible.builtin.file:
        path: "{{ docker_registry_purger_base_path }}"
        state: absent
