# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if required ddclient settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - ddclient_uid
    - ddclient_gid
    - ddclient_container_network
    - ddclient_registry_url
